# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tango < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/golang-mods/tango/releases/download/v1.0.0/tango_Darwin_arm64.tar.gz"
      sha256 "aecf0b0814588d8e42af40d1a26d581b8b0547ff02362b6e6041a49d0e6bd68d"

      def install
        bin.install "tango"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-mods/tango/releases/download/v1.0.0/tango_Darwin_x86_64.tar.gz"
      sha256 "7fa43d45439f3a3692cb5017e174f0d4d1dee8e049ffa2487119f27619d498de"

      def install
        bin.install "tango"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/golang-mods/tango/releases/download/v1.0.0/tango_Linux_arm64.tar.gz"
      sha256 "4cf38015d8fffd2115834d3a754e0ca8ff64d106069c49bfde25b4d3cece1ab4"

      def install
        bin.install "tango"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/golang-mods/tango/releases/download/v1.0.0/tango_Linux_x86_64.tar.gz"
      sha256 "8326864386ed869f90523c9bc5bd0c31862be13a9a9cebdc25c66b017ee36236"

      def install
        bin.install "tango"
      end
    end
  end
end
